#!/usr/bin/env python3
"""wasmtune Unsloth trainer (NVIDIA CUDA): SFT + DPO + GRPO via TRL.

Generated by `finetune train` (backend=unsloth). Reads the same JSONL files
Node's dataset step wrote: .finetune/dataset.{sft,dpo,grpo}.jsonl plus a small
args file passed as --args-json.
"""
import argparse
import json
import os
import sys


def load_args(path):
    with open(path) as f:
        return json.load(f)


def to_hf_dataset(rows, kind):
    from datasets import Dataset
    if kind == "sft":
        texts = []
        for r in rows:
            msgs = r.get("messages", [])
            t = ""
            for m in msgs:
                role = m.get("role", "user")
                t += f"<|{role}|>\n{m.get('content','')}\n"
            texts.append({"text": t})
        return Dataset.from_list(texts)
    if kind == "dpo" or kind == "orpo":
        return Dataset.from_list([
            {"prompt": r["prompt"], "chosen": r["chosen"], "rejected": r["rejected"]}
            for r in rows if r.get("prompt") and r.get("chosen") and r.get("rejected")
        ])
    # grpo: prompts only; rewards come from --reward-py (python fn) if provided
    return Dataset.from_list([{"prompt": r["prompt"]} for r in rows if r.get("prompt")])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--args-json", required=True)
    args = ap.parse_args()
    cfg = load_args(args.args_json)

    model_id = cfg["model"]
    method = cfg.get("method", "sft")
    out = cfg["outDir"]
    os.makedirs(out, exist_ok=True)

    try:
        from unsloth import FastLanguageModel
    except Exception as e:
        print("ERROR: Unsloth import failed. NVIDIA + CUDA required for this backend.", file=sys.stderr)
        print(f"Underlying error: {e}", file=sys.stderr)
        print("On Apple Silicon re-run with training.backend=mlx. See requirements-cuda.txt.", file=sys.stderr)
        sys.exit(2)

    import torch
    if not torch.cuda.is_available():
        print("ERROR: torch.cuda.is_available() is False — Unsloth needs an NVIDIA GPU.", file=sys.stderr)
        sys.exit(2)

    max_seq = int(cfg.get("maxSeqLen", 2048))
    lora = cfg.get("lora", {})
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_id,
        max_seq_length=max_seq,
        dtype=None,
        load_in_4bit=bool(cfg.get("quant4", True)),
    )
    model = FastLanguageModel.get_peft_model(
        model,
        r=int(lora.get("r", 16)),
        target_modules=None,  # auto per architecture
        lora_alpha=int(lora.get("alpha", 16)),
        lora_dropout=float(lora.get("dropout", 0.05)),
        bias="none",
        use_gradient_checkpointing="unsloth",
    )

    ds_path = {"sft": cfg["sftFile"], "dpo": cfg["dpoFile"], "orpo": cfg["dpoFile"], "grpo": cfg["grpoFile"]}[method]
    with open(ds_path) as f:
        rows = [json.loads(l) for l in f if l.strip()]
    if cfg.get("maxSteps", 0) and cfg.get("dryRun"):
        rows = rows[:8]
        print(f"[dry-run] {method}: {len(rows)} rows, no optimizer steps", file=sys.stderr)
        with open(os.path.join(out, "dry_run.json"), "w") as f:
            json.dump({"method": method, "rows": len(rows), "model": model_id}, f, indent=2)
        return
    dataset = to_hf_dataset(rows, method)

    if method == "sft":
        from trl import SFTConfig, SFTTrainer
        targs = SFTConfig(
            output_dir=out, num_train_epochs=float(cfg.get("epochs", 2)),
            per_device_train_batch_size=int(cfg.get("batchSize", 2)),
            gradient_accumulation_steps=int(cfg.get("gradAccum", 4)),
            learning_rate=float(cfg.get("lr", 2e-4)),
            max_steps=int(cfg.get("maxSteps", -1) or -1),
            seed=int(cfg.get("seed", 42)),
            dataset_text_field="text", max_seq_length=max_seq,
            logging_steps=10, save_steps=200, report_to="none",
        )
        trainer = SFTTrainer(model=model, tokenizer=tokenizer, train_dataset=dataset, args=targs)
    elif method == "dpo":
        from trl import DPOConfig, DPOTrainer
        targs = DPOConfig(
            output_dir=out, beta=float(cfg.get("beta", 0.1)),
            per_device_train_batch_size=int(cfg.get("batchSize", 2)),
            gradient_accumulation_steps=int(cfg.get("gradAccum", 4)),
            learning_rate=float(cfg.get("lr", 5e-7)),
            max_steps=int(cfg.get("maxSteps", -1) or -1),
            seed=int(cfg.get("seed", 42)), report_to="none",
        )
        trainer = DPOTrainer(model=model, ref_model=None, train_dataset=dataset, processing_class=tokenizer, args=targs)
    elif method == "orpo":
        # ORPO needs no reference model (single-model odds-ratio loss).
        from trl import ORPOConfig, ORPOTrainer
        targs = ORPOConfig(
            output_dir=out, beta=float(cfg.get("beta", 0.1)),
            per_device_train_batch_size=int(cfg.get("batchSize", 2)),
            gradient_accumulation_steps=int(cfg.get("gradAccum", 4)),
            learning_rate=float(cfg.get("lr", 8e-6)),
            max_steps=int(cfg.get("maxSteps", -1) or -1),
            seed=int(cfg.get("seed", 42)), report_to="none",
        )
        trainer = ORPOTrainer(model=model, train_dataset=dataset, processing_class=tokenizer, args=targs)
    else:
        from trl import GRPOConfig, GRPOTrainer
        reward_fn = None
        rpy = cfg.get("rewardPy")
        if rpy and os.path.exists(rpy):
            import importlib.util
            spec = importlib.util.spec_from_file_location("site_reward", rpy)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            reward_fn = getattr(mod, "reward", None)
        if reward_fn is None:
            reward_fn = lambda prompts, completions, **kw: [min(len(c) / 500, 1.0) for c in completions]
        targs = GRPOConfig(
            output_dir=out, num_generations=int(cfg.get("numGenerations", 4)),
            per_device_train_batch_size=int(cfg.get("batchSize", 2)),
            learning_rate=float(cfg.get("lr", 5e-6)),
            max_steps=int(cfg.get("maxSteps", -1) or -1),
            seed=int(cfg.get("seed", 42)), report_to="none",
        )
        trainer = GRPOTrainer(model=model, processing_class=tokenizer, reward_funcs=[reward_fn], train_dataset=dataset, args=targs)

    trainer.train()
    model.save_pretrained(os.path.join(out, "adapters"))
    tokenizer.save_pretrained(os.path.join(out, "adapters"))
    # Merge for convert step (16-bit; quantization happens in convert).
    try:
        merged = model.merge_and_unload()
        merged.save_pretrained(os.path.join(out, "merged"))
        tokenizer.save_pretrained(os.path.join(out, "merged"))
    except Exception as e:
        print(f"WARNING: merge_and_unload failed ({e}); adapters still saved.", file=sys.stderr)
    with open(os.path.join(out, "train.report.json"), "w") as f:
        json.dump({"method": method, "model": model_id, "backend": "unsloth"}, f, indent=2)
    print(f"done -> {out}")


if __name__ == "__main__":
    main()
